main: CustomExplosion
name: CustomExplosion
version: 1.0.0
description: A plugin for overriding explosion events.
load: POSTWORLD
api-version: 1.16
author: MrFlyingPizza

commands:
  genplanet:
    description: generate planet
    usage: /<command> radius height numberofwaves waveheight